apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: demosecret
  containers:
    - name: nginx-container
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret