apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
spec:
  selector: 
    tier: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 9999
      targetPort: 3000
      nodePort: 30003
